Варіант 1
1, 6, 7, 9,
10, 11, 15,
17, 18

In [22]:
import numpy as np
import random
# Task 1

# 1
def task_1(n):
    a = np.array([x+1 for x in range(n)])
    return np.diag(a)

def task_1_py(n):
    a = [
        [i + 1 if i == j else 0 for i in range(n)]
        for j in range(n)
    ]
    return a

In [2]:
%timeit -n 100 task_1(100)

21.2 µs ± 6.77 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [3]:

%timeit -n 100 task_1_py(100)

501 µs ± 27.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
def task_6(a):
    r = np.array(a)
    r[r > 0] = -1
    return r

def task_6_py(a):
    r = [-1 if i > 0 else 0 for i in a]
    return r

In [11]:
arr = [3, 4, 0, 9, 7, 0, 6, 0, 4, 0, 3]

In [12]:
%timeit -n 100 task_6(arr)

3.82 µs ± 157 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [13]:
%timeit -n 100 task_6_py(arr)

902 ns ± 57.4 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [14]:
def task_7(a):
    r = np.array(a)
    r[r == 0] = -1
    return r

def task_7_py(a):
    r = [-1 if i == 0 else 0 for i in a]
    return r


In [15]:
arr = [3, 4, 0, 9, 7, 0, 6, 0, 4, 0, 3]


In [16]:
%timeit -n 100 task_6(arr)

3.26 µs ± 354 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [17]:
%timeit -n 100 task_6_py(arr)

646 ns ± 15.9 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
def task_9(n):
    start_time = time.time()
    arr = np.arange(n, -1, -1)
    end_time = time.time()
    execution_time = end_time - start_time
    return arr, execution_time

In [23]:
import time

In [24]:
arr_numpy, time_numpy = task_9(10)
print("Масив (NumPy):", arr_numpy)
print("Час виконання (NumPy):", time_numpy)

Масив (NumPy): [10  9  8  7  6  5  4  3  2  1  0]
Час виконання (NumPy): 3.910064697265625e-05


In [26]:
def task_9_2(n):
    start_time = time.time()
    arr = [i for i in range(n, -1, -1)]
    end_time = time.time()
    execution_time = end_time - start_time
    return arr, execution_time

n = int(input("Введіть число n: "))
arr_iterative, time_iterative = task_9_2(n)
print("Масив (ітеративно):", arr_iterative)
print("Час виконання (ітеративно):", time_iterative)

Введіть число n: 10
Масив (ітеративно): [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
Час виконання (ітеративно): 5.0067901611328125e-06


In [27]:
def numpy_approach_task11(n):
    start_time = time.time()
    arr = np.ones((n, n), dtype=int)
    arr[1:-1, 1:-1] = 0
    end_time = time.time()
    execution_time = end_time - start_time
    return arr, execution_time

n = int(input("Введіть число n: "))
arr_numpy, time_numpy = numpy_approach_task11(n)
print("Масив з рамкою (NumPy):")
print(arr_numpy)
print("Час виконання (NumPy):", time_numpy)

Введіть число n: 10
Масив з рамкою (NumPy):
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]
Час виконання (NumPy): 5.1021575927734375e-05


In [28]:
import time

def iterative_approach_task11(n):
    start_time = time.time()
    arr = [[1]*n for _ in range(n)]
    for i in range(1, n-1):
        for j in range(1, n-1):
            arr[i][j] = 0
    end_time = time.time()
    execution_time = end_time - start_time
    return arr, execution_time

n = int(input("Введіть число n: "))
arr_iterative, time_iterative = iterative_approach_task11(n)
print("Масив з рамкою (ітеративно):")
for row in arr_iterative:
    print(row)
print("Час виконання (ітеративно):", time_iterative)


Введіть число n: 10
Масив з рамкою (ітеративно):
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 1]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 1]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 1]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 1]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 1]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 1]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 1]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Час виконання (ітеративно): 2.2172927856445312e-05


In [29]:
def numpy_approach_task15(p, l):
    start_time = time.time()
    arr = np.ones((p, l), dtype=int)
    arr[:, ::2] = 0
    end_time = time.time()
    execution_time = end_time - start_time
    return arr, execution_time

p = int(input("Введіть кількість рядків (p): "))
l = int(input("Введіть кількість стовпчиків (l): "))
arr_numpy, time_numpy = numpy_approach_task15(p, l)
print("Матриця (NumPy):")
print(arr_numpy)
print("Час виконання (NumPy):", time_numpy)

Введіть кількість рядків (p): 10
Введіть кількість стовпчиків (l): 10
Матриця (NumPy):
[[0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]]
Час виконання (NumPy): 3.910064697265625e-05


In [30]:
def iterative_approach_task15(p, l):
    start_time = time.time()
    arr = [[1 if j % 2 == 0 else 0 for j in range(l)] for i in range(p)]
    end_time = time.time()
    execution_time = end_time - start_time
    return arr, execution_time

p = int(input("Введіть кількість рядків (p): "))
l = int(input("Введіть кількість стовпчиків (l): "))
arr_iterative, time_iterative = iterative_approach_task15(p, l)
print("Матриця (ітеративно):")
for row in arr_iterative:
    print(row)
print("Час виконання (ітеративно):", time_iterative)

Введіть кількість рядків (p): 10
Введіть кількість стовпчиків (l): 10
Матриця (ітеративно):
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
Час виконання (ітеративно): 1.5020370483398438e-05


In [32]:
def numpy_approach_task17(p):
    start_time = time.time()
    vec = np.arange(p)
    mask = (vec < p/2) | (vec > 3*p/4)
    vec[mask] *= -1
    end_time = time.time()
    execution_time = end_time - start_time
    return vec, execution_time

p = int(input("Введіть значення p: "))
vec_numpy, time_numpy = numpy_approach_task17(p)
print("Вектор (NumPy):", vec_numpy)
print("Час виконання (NumPy):", time_numpy)

Введіть значення p: 3
Вектор (NumPy): [ 0 -1  2]
Час виконання (NumPy): 0.0001709461212158203


In [33]:
def iterative_approach_task17(p):
    start_time = time.time()
    vec = list(range(p))
    for i in range(p):
        if vec[i] < p/2 or vec[i] > 3*p/4:
            vec[i] *= -1
    end_time = time.time()
    execution_time = end_time - start_time
    return vec, execution_time

p = int(input("Введіть значення p: "))
vec_iterative, time_iterative = iterative_approach_task17(p)
print("Вектор (ітеративно):", vec_iterative)
print("Час виконання (ітеративно):", time_iterative)

Введіть значення p: 3
Вектор (ітеративно): [0, -1, 2]
Час виконання (ітеративно): 6.198883056640625e-06


In [34]:
def numpy_approach_task18(size):
    start_time = time.time()
    vec = np.random.randint(0, 100, size=size)
    unique_count = len(np.unique(vec))
    end_time = time.time()
    execution_time = end_time - start_time
    return unique_count, execution_time

size = int(input("Введіть розмір вектора: "))
unique_count_numpy, time_numpy = numpy_approach_task18(size)
print("Кількість унікальних чисел (NumPy):", unique_count_numpy)
print("Час виконання (NumPy):", time_numpy)

Введіть розмір вектора: 4
Кількість унікальних чисел (NumPy): 4
Час виконання (NumPy): 0.00032019615173339844


In [36]:
def iterative_approach_task18(size):
    start_time = time.time()
    vec = [random.randint(0, 99) for _ in range(size)]
    unique_count = len(set(vec))
    end_time = time.time()
    execution_time = end_time - start_time
    return unique_count, execution_time

size = int(input("Введіть розмір вектора: "))
unique_count_iterative, time_iterative = iterative_approach_task18(size)
print("Кількість унікальних чисел (ітеративно):", unique_count_iterative)
print("Час виконання (ітеративно):", time_iterative)

Введіть розмір вектора: 3
Кількість унікальних чисел (ітеративно): 3
Час виконання (ітеративно): 4.696846008300781e-05


In [37]:
def solve(matrix):
    b = matrix[:, -1]
    det = matrix[:, :-1]
    dets = []
    for i in range(matrix.shape[0]):
        det_i = det.copy()
        det_i[:, i] = b
        dets.append(det_i)
    det = np.linalg.det(det)
    dets = [np.linalg.det(d) for d in dets]
    solution = [d / det for d in dets]
    return np.array(solution)

matrix = [
    [1, 1, 2, 3, 1],
    [3, -1, -1, -2, -4],
    [2, -3, -1, -1, -6],
    [1, 2, 3, -1, 4]
]
matrix = np.array(matrix)

In [38]:
print(np.allclose(solve(matrix), np.linalg.solve(matrix[:, :-1], matrix[:, -1])))
inv = np.linalg.inv(matrix[:, :-1])
inv

True


array([[ 1.85185185e-01,  3.33333333e-01, -7.40740741e-02,
        -3.70370370e-02],
       [ 3.70370370e-02,  3.33333333e-01, -4.81481481e-01,
        -7.40740741e-02],
       [ 9.59451997e-18, -3.33333333e-01,  3.33333333e-01,
         3.33333333e-01],
       [ 2.59259259e-01,  0.00000000e+00, -3.70370370e-02,
        -1.85185185e-01]])

In [62]:
def add_mat(mat1, mat2):
    result = []
    for i in range(len(mat1)):
        row = []
        for j in range(len(mat1[0])):
            row.append(mat1[i][j] + mat2[i][j])
        result.append(row)

    return result

def mult_mat(mat1, mat2):
    result = []
    for i in range(len(mat1)):
        row = []
        for j in range(len(mat2[0])):
            sum = 0
            for k in range(len(mat2)):
                sum += mat1[i][k] * mat2[k][j]
            row.append(sum)
        result.append(row)

    return result

def mult_mat_const(mat, const):
    return [[i * const for i in j] for j in mat]

def solve_np(a, b):
    return  np.matmul(2 * (a + b), (2 * b - a))

def solve_py(a, b):
    return mult_mat_const(mult_mat(add_mat(a, b), add_mat(mult_mat_const(b,2), mult_mat_const(a, -1))),2)

In [63]:
A = [
    [2, 3, -1],
    [4, 5, 2],
    [-1, 0, 7]
]
B = [
    [-1, 0, 5],
    [0, 1, 3],
    [2, -2, 4]
]
A_np, B_np = np.array(A), np.array(B)
np.allclose(solve_py(A, B), solve_np(A_np, B_np))

True

In [64]:
solve_py(A, B)

[[8, -56, 54], [-30, -100, 146], [118, -82, 28]]

In [65]:
solve_np(A_np, B_np)

array([[   8,  -56,   54],
       [ -30, -100,  146],
       [ 118,  -82,   28]])

In [66]:
%timeit -n 100 solve_np(A_np, B_np)
%timeit -n 100 solve_py(A, B)

The slowest run took 4.05 times longer than the fastest. This could mean that an intermediate result is being cached.
9.05 µs ± 4.28 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
16.2 µs ± 3.07 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
